- name: ' create tsx_template / touch /home/stack/templates/extra_tsx_template.yaml '
  ansible.builtin.shell: |
    touch /home/stack/templates/extra_tsx_template.yaml
  register: results_validate
- debug:
    var: results_validate.stdout_lines

- name: ' put conf in tsx_template'
  ansible.builtin.blockinfile:
    path: /home/stack/templates/extra_tsx_template.yaml
    block: |
      parameter_defaults:
          ComputeParameters:
              KernelArgs: "tsx=off"
  register: results_validate
- debug:
    var: results_validate.stdout_lines

- name: ' During upgrade Leapp by Framework For Upgrade, openvswitch failed to start with error / rm -f /etc/systemd/system/ovs* '
  ansible.builtin.shell: |
    sudo cp -r /etc/systemd/system/ovs /tmp/ovs_temp/
    sudo rm -rf /etc/systemd/system/ovs/*
  register: results_validate
- debug:
    var: results_validate.stdout_lines


# After Leapp Upgrade

- name: ' An FFU may randomly fail during the deploy step (after LEAPP and Upgrade itself) due to wrong SELinux labels associated to directory content / chcon -R -t container_file_t /var/lib/* '
  ansible.builtin.shell: |
    chcon -R -t container_file_t /var/log/containers/
    chcon -R -t container_file_t /var/lib/mysql
    chcon -R -t container_file_t /var/lib/redis
    chcon -R -t container_file_t /var/lib/haproxy
    chcon -R -t container_file_t /var/lib/manila
    chcon -R -t container_file_t /var/lib/openvswitch/ovn
    chcon -R -t container_file_t /var/lib/rabbitmq
  register: results_validate
- debug:
    var: results_validate.stdout_lines

# Disable repo

- name: ' The advanced-virt-for-rhel-8-x86_64-rpms and advanced-virt-for-rhel-8-x86_64-eus-rpms repos have been removed from the documentation as required repos for the Undercloud and the Overcloud / subscription-manager repos --disable '
  ansible.builtin.shell: |
    sudo su -
    subscription-manager repos --disable advanced-virt-for-rhel-8-x86_64-rpms
    subscription-manager repos --disable advanced-virt-for-rhel-8-x86_64-eus-rpms
    dnf module disable -y virt:8.2
    dnf module enable -y virt:rhel
    dnf distro-sync
    yum clean all
  register: results_validate
- debug:
    var: results_validate.stdout_lines


# Known_Issue_5: (optional) BZ#2024447 - Identity service (keystone) password for the placement user was overridden by NovaPassword during FFU RHOSP 13 to 16   ???????

- name: ' Live migration fails due to qemu error during in-place upgrade / touch /home/stack/templates/extra_nova_template.yaml '
  ansible.builtin.shell: |
    touch /home/stack/templates/extra_tsx_template.yaml
  register: results_validate
- debug:
    var: results_validate.stdout_lines

- name: ' Put conf in /home/stack/templates/extra_nova_template.yaml '
  ansible.builtin.blockinfile:
    path: /home/stack/templates/extra_nova_template.yaml
    block: |
      parameter_defaults:
        ComputeExtraConfig:
          nova::compute::libvirt::max_queues: 8
  register: results_validate
- debug:
    var: results_validate.stdout_lines

- name: ' BZ#2141393 - cephvolumescan actor fails / touch /home/stack/templates/extra_leapp_template.yaml '
  ansible.builtin.shell: |
    touch /home/stack/templates/extra_leapp_template.yaml
  register: results_validate
- debug:
    var: results_validate.stdout_lines
    
- name: ' BZ#2141393 - cephvolumescan actor fails / touch /home/stack/templates/extra_leapp_template.yaml '
  ansible.builtin.blockinfile:
    path: /home/stack/templates/extra_leapp_template.yaml
    block: |
      parameter_defaults:
        LeappActorsToRemove: ['cephvolumescan']
  register: results_validate
- debug:
    var: results_validate.stdout_lines
